# -*- coding: utf-8 -*-
"""ยินดีต้อนรับสู่ Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb

# ส่วนใหม่
"""

"""
HW3 สรุปลัธธ์การคำนวณ - Search Algorithms
1. Breadth First Tree Search
2. Depth First Tree Search
3. Breadth First Search (Graph)
4. Depth First Graph Search
5. Best First Graph Search
6. Uniform Cost Search
7. Depth Limited Search
8. Iterative Deepening Search
9. Greedy Best First Search
10. A*-Search
11. Recursive Best First Search

ทดสอบด้วยปัญหา: หาเส้นทางจาก Arad ไป Vaslui บนแผนที่ Romania
"""

import heapq
import math
from collections import deque

romania_map = {
    'Arad': {'Zerind': 75, 'Sibiu': 140, 'Timisoara': 118},
    'Zerind': {'Arad': 75, 'Oradea': 71},
    'Oradea': {'Zerind': 71, 'Sibiu': 151},
    'Sibiu': {'Arad': 140, 'Oradea': 151, 'Fagaras': 99, 'Rimnicu Vilcea': 80},
    'Timisoara': {'Arad': 118, 'Lugoj': 111},
    'Lugoj': {'Timisoara': 111, 'Mehadia': 70},
    'Mehadia': {'Lugoj': 70, 'Drobeta': 75},
    'Drobeta': {'Mehadia': 75, 'Craiova': 120},
    'Craiova': {'Drobeta': 120, 'Rimnicu Vilcea': 146, 'Pitesti': 138},
    'Rimnicu Vilcea': {'Sibiu': 80, 'Craiova': 146, 'Pitesti': 97},
    'Fagaras': {'Sibiu': 99, 'Bucharest': 211},
    'Pitesti': {'Rimnicu Vilcea': 97, 'Craiova': 138, 'Bucharest': 101},
    'Bucharest': {'Fagaras': 211, 'Pitesti': 101, 'Giurgiu': 90, 'Urziceni': 85},
    'Giurgiu': {'Bucharest': 90},
    'Urziceni': {'Bucharest': 85, 'Hirsova': 98, 'Vaslui': 142},
    'Hirsova': {'Urziceni': 98, 'Eforie': 86},
    'Eforie': {'Hirsova': 86},
    'Vaslui': {'Urziceni': 142, 'Iasi': 92},
    'Iasi': {'Vaslui': 92, 'Neamt': 87},
    'Neamt': {'Iasi': 87},
}

locations = {
    'Arad': (91, 492), 'Bucharest': (400, 327), 'Craiova': (253, 288),
    'Drobeta': (165, 299), 'Eforie': (562, 293), 'Fagaras': (305, 449),
    'Giurgiu': (375, 270), 'Hirsova': (534, 350), 'Iasi': (473, 506),
    'Lugoj': (165, 379), 'Mehadia': (168, 339), 'Neamt': (406, 537),
    'Oradea': (131, 571), 'Pitesti': (320, 368), 'Rimnicu Vilcea': (233, 410),
    'Sibiu': (207, 457), 'Timisoara': (94, 410), 'Urziceni': (456, 350),
    'Vaslui': (509, 444), 'Zerind': (108, 531),
}

START, GOAL = 'Arad', 'Vaslui'

def heuristic(city, goal=GOAL):
    """straight-line distance heuristic ไปยัง goal"""
    (x1, y1), (x2, y2) = locations[city], locations[goal]
    return math.hypot(x1 - x2, y1 - y2)


class Node:
    __slots__ = ('state', 'parent', 'cost', 'depth')

    def __init__(self, state, parent=None, cost=0, depth=0):
        self.state = state
        self.parent = parent
        self.cost = cost
        self.depth = depth

    def path(self):
        node, result = self, []
        while node:
            result.append(node.state)
            node = node.parent
        return list(reversed(result))

    def expand(self, graph):
        children = []
        for neighbor, dist in graph.get(self.state, {}).items():
            children.append(Node(neighbor, self, self.cost + dist, self.depth + 1))
        return children


def report(name, node, nodes_expanded, results):
    if node is None:
        print(f"[{name}] ไม่พบเส้นทาง")
        results.append((name, "-", None, nodes_expanded))
        return
    path = node.path()
    print(f"[{name}]")
    print("  เส้นทาง :", " -> ".join(path))
    print(f"  ระยะทางรวม : {node.cost}")
    print(f"  จำนวน node ที่ขยาย : {nodes_expanded}\n")
    results.append((name, " -> ".join(path), node.cost, nodes_expanded))



# 1. Breadth First Tree Search
def breadth_first_tree_search(graph, start, goal):
    frontier = deque([Node(start)])
    expanded = 0
    while frontier:
        node = frontier.popleft()
        expanded += 1
        if node.state == goal:
            return node, expanded
        frontier.extend(node.expand(graph))
    return None, expanded


# 2. Depth First Tree Search
def depth_first_tree_search(graph, start, goal):
    frontier = [Node(start)]
    expanded = 0
    while frontier:
        node = frontier.pop()
        expanded += 1
        if node.state == goal:
            return node, expanded
        frontier.extend(node.expand(graph))
    return None, expanded


# 3. Breadth First (Graph) Search
def breadth_first_graph_search(graph, start, goal):
    node = Node(start)
    if node.state == goal:
        return node, 1
    frontier = deque([node])
    explored = set()
    expanded = 0
    while frontier:
        node = frontier.popleft()
        explored.add(node.state)
        expanded += 1
        for child in node.expand(graph):
            if child.state not in explored and child.state not in [n.state for n in frontier]:
                if child.state == goal:
                    return child, expanded
                frontier.append(child)
    return None, expanded


# 4. Depth First Graph Search
def depth_first_graph_search(graph, start, goal):
    frontier = [Node(start)]
    explored = set()
    expanded = 0
    while frontier:
        node = frontier.pop()
        expanded += 1
        if node.state == goal:
            return node, expanded
        explored.add(node.state)
        frontier.extend(child for child in node.expand(graph)
                         if child.state not in explored)
    return None, expanded


# generic Best First Graph Search
def best_first_graph_search(graph, start, goal, f):
    counter = 0  # ใช้กันชนกรณี f เท่ากัน (tie-breaker)
    start_node = Node(start)
    frontier = [(f(start_node), counter, start_node)]
    explored = {}
    expanded = 0
    while frontier:
        _, _, node = heapq.heappop(frontier)
        expanded += 1
        if node.state == goal:
            return node, expanded
        if node.state in explored and explored[node.state] <= node.cost:
            continue
        explored[node.state] = node.cost
        for child in node.expand(graph):
            counter += 1
            heapq.heappush(frontier, (f(child), counter, child))
    return None, expanded


# 5. Best First Graph Search
def best_first_search_demo(graph, start, goal):
    return best_first_graph_search(graph, start, goal, f=lambda n: heuristic(n.state))


# 6. Uniform Cost Search
def uniform_cost_search(graph, start, goal):
    return best_first_graph_search(graph, start, goal, f=lambda n: n.cost)


# 7. Depth Limited Search
def depth_limited_search(graph, start, goal, limit=10):
    expanded = 0

    def recursive_dls(node, limit):
        nonlocal expanded
        expanded += 1
        if node.state == goal:
            return node
        elif limit == 0:
            return 'cutoff'
        else:
            cutoff_occurred = False
            for child in node.expand(graph):
                result = recursive_dls(child, limit - 1)
                if result == 'cutoff':
                    cutoff_occurred = True
                elif result is not None:
                    return result
            return 'cutoff' if cutoff_occurred else None

    result = recursive_dls(Node(start), limit)
    return (result if result != 'cutoff' else None), expanded


# 8. Iterative Deepening Search
def iterative_deepening_search(graph, start, goal, max_depth=30):
    total_expanded = 0
    for depth in range(max_depth):
        result, expanded = depth_limited_search(graph, start, goal, depth)
        total_expanded += expanded
        if result is not None:
            return result, total_expanded
    return None, total_expanded


# 9. Greedy Best First Search
def greedy_best_first_search(graph, start, goal):
    return best_first_graph_search(graph, start, goal, f=lambda n: heuristic(n.state))


# 10. A*-Search: f(n) = g(n) + h(n)
def astar_search(graph, start, goal):
    return best_first_graph_search(graph, start, goal, f=lambda n: n.cost + heuristic(n.state))


# 11. Recursive Best First Search
def recursive_best_first_search(graph, start, goal):
    expanded = 0

    def rbfs(node, f_node, f_limit):
        nonlocal expanded
        expanded += 1
        if node.state == goal:
            return node, 0
        successors = node.expand(graph)
        if not successors:
            return None, math.inf
        f_values = {}
        for child in successors:
            f_values[child.state] = max(child.cost + heuristic(child.state), f_node)

        while True:
            successors.sort(key=lambda n: f_values[n.state])
            best = successors[0]
            if f_values[best.state] > f_limit:
                return None, f_values[best.state]
            alternative = f_values[successors[1].state] if len(successors) > 1 else math.inf
            result, best_f = rbfs(best, f_values[best.state], min(f_limit, alternative))
            f_values[best.state] = best_f
            if result is not None:
                return result, best_f

    start_node = Node(start)
    result, _ = rbfs(start_node, heuristic(start), math.inf)
    return result, expanded


if __name__ == "__main__":

    results = []

    node, exp = breadth_first_tree_search(romania_map, START, GOAL)
    report("1. Breadth First Tree Search", node, exp, results)

    node, exp = depth_first_tree_search(romania_map, START, GOAL)
    report("2. Depth First Tree Search", node, exp, results)

    node, exp = breadth_first_graph_search(romania_map, START, GOAL)
    report("3. Breadth First Search (Graph)", node, exp, results)

    node, exp = depth_first_graph_search(romania_map, START, GOAL)
    report("4. Depth First Graph Search", node, exp, results)

    node, exp = best_first_search_demo(romania_map, START, GOAL)
    report("5. Best First Graph Search", node, exp, results)

    node, exp = uniform_cost_search(romania_map, START, GOAL)
    report("6. Uniform Cost Search", node, exp, results)

    node, exp = depth_limited_search(romania_map, START, GOAL, limit=10)
    report("7. Depth Limited Search (limit=10)", node, exp, results)

    node, exp = iterative_deepening_search(romania_map, START, GOAL)
    report("8. Iterative Deepening Search", node, exp, results)

    node, exp = greedy_best_first_search(romania_map, START, GOAL)
    report("9. Greedy Best First Search", node, exp, results)

    node, exp = astar_search(romania_map, START, GOAL)
    report("10. A*-Search", node, exp, results)

    node, exp = recursive_best_first_search(romania_map, START, GOAL)
    report("11. Recursive Best First Search", node, exp, results)